### ISSUE TITLE
Question about usage.

### ISSUE THREAD

**Issue by kylebrowning** [wilbertliu/NavigationKit#1]
Can this library be used to achieve something like this?

![3ohhwevwkgphtrjaxy](https://user-images.githubusercontent.com/113023/30619150-a2c48cba-9d52-11e7-8701-c7a8aa02a0aa.gif)

**Comment by wilbertliu** [comment]
Hey @kylebrowning 👋🏻

To answer your question, yes, it can. What should you do is setting `barBackgroundColor` to `.clear` in your respective controller. The rest should be obvious.

Just let me know if you have more questions 😊

**Comment by kylebrowning** [comment]
@wilbertliu What about the height of the navigation controller?

**Comment by wilbertliu** [comment]
@kylebrowning We don't change any of that.
